name: Sync forks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
    sync:
        name: Sync forks with upstream
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Sync
              run: scripts/sync-fork.sh
              env:
                GH_PAT: ${{ secrets.GH_PAT }}
